version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=/app/data/bot.db
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "test", "-f", "/app/data/bot.db"]
      interval: 30s
      timeout: 10s
      retries: 3